function [C] = out_lieC(q,dq)

  C(1,1)=dq(3)*((cos(q(1))*sin(q(2)) + 2*cos(q(2))*sin(q(1)) - sin(q(1))*(cos(q(2)) - 1))*...
         (cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) + cos(q(1))) + (sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) +...
          sin(q(1)))*(sin(q(1))*sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1))) - dq(2)*(cos(q(1))*...
         (sin(q(1) + q(2) + q(3)) + 2*sin(q(1) + q(2)) + 2*sin(q(1))) - sin(q(1))*(cos(q(1) + q(2) + q(3)) + 2*...
         cos(q(1) + q(2)) + 2*cos(q(1))));
  C(1,2)=dq(3)*(((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)))*(cos(q(1)) - 2*cos(q(1))*...
         cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - ((cos(q(1) + q(2) + q(3)) + cos(q(1) +...
          q(2)) + cos(q(1)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*(cos(q(2)) -...
          1)))/2 + ((cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)))*(cos(q(1))*sin(q(2)) + 2*cos(q(2))*sin(q(1)) -...
          sin(q(1))*(cos(q(2)) - 1)))/2 + ((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(sin(q(1))*sin(q(2)) - 2*...
         cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 + (sin(q(1))*(cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) +...
          cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - (cos(q(1))*...
         (sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) +...
          sin(q(1))*(cos(q(2)) - 1)))/2) - dq(1)*(cos(q(1))*(sin(q(1) + q(2) + q(3)) + 2*sin(q(1) + q(2)) + 2*...
         sin(q(1))) - sin(q(1))*(cos(q(1) + q(2) + q(3)) + 2*cos(q(1) + q(2)) + 2*cos(q(1)))) + dq(2)*(sin(q(1))*...
         (cos(q(1) + q(2) + q(3)) + 2*cos(q(1) + q(2))) - cos(q(1))*(sin(q(1) + q(2) + q(3)) + 2*sin(q(1) + q(2))));
  C(1,3)=dq(3)*((sin(q(1))*sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1))*...
         (sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) +...
          sin(q(1))*(cos(q(2)) - 1)) + (cos(q(1))*sin(q(2)) + 2*cos(q(2))*sin(q(1)) - sin(q(1))*(cos(q(2)) - 1))*...
         (cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) + cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) +...
          cos(q(1))*(cos(q(2)) - 1))) + dq(2)*(((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)))*(cos(q(1)) - 2*...
         cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - ((cos(q(1) + q(2) + q(3)) +...
          cos(q(1) + q(2)) + cos(q(1)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*...
         (cos(q(2)) - 1)))/2 + ((cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)))*(cos(q(1))*sin(q(2)) + 2*cos(q(2))*...
         sin(q(1)) - sin(q(1))*(cos(q(2)) - 1)))/2 + ((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(sin(q(1))*...
         sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 + (sin(q(1))*(cos(q(1) + q(2) + q(3)) +...
          cos(q(1) + q(2)) + cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 -...
          (cos(q(1))*(sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*...
         sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)))/2) + dq(1)*((cos(q(1))*sin(q(2)) + 2*cos(q(2))*sin(q(1)) - sin(q(1))*...
         (cos(q(2)) - 1))*(cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) + cos(q(1))) + (sin(q(1) + q(2) + q(3)) +...
          sin(q(1) + q(2)) + sin(q(1)))*(sin(q(1))*sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)));
  C(2,1)=dq(1)*(cos(q(1))*(sin(q(1) + q(2) + q(3)) + 2*sin(q(1) + q(2)) + 2*sin(q(1))) - sin(q(1))*...
         (cos(q(1) + q(2) + q(3)) + 2*cos(q(1) + q(2)) + 2*cos(q(1)))) + dq(3)*(((sin(q(1) + q(2) + q(3)) + sin(q(1) +...
          q(2)) + sin(q(1)))*(cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) -...
          1)))/2 - ((cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) + cos(q(1)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*...
         cos(q(2))*sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)))/2 + ((cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)))*...
         (cos(q(1))*sin(q(2)) + 2*cos(q(2))*sin(q(1)) - sin(q(1))*(cos(q(2)) - 1)))/2 + ((sin(q(1) + q(2) + q(3)) +...
          sin(q(1) + q(2)))*(sin(q(1))*sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - (sin(q(1))*...
         (cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) + cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) +...
          cos(q(1))*(cos(q(2)) - 1)))/2 + (cos(q(1))*(sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) -...
          cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)))/2);
  C(2,2)=dq(3)*((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(cos(q(1)) - 2*cos(q(1))*cos(q(2)) +...
          sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)) - (cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)))*(sin(q(1)) -...
          cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)));
  C(2,3)=dq(1)*(((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)))*(cos(q(1)) - 2*cos(q(1))*...
         cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - ((cos(q(1) + q(2) + q(3)) + cos(q(1) +...
          q(2)) + cos(q(1)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*(cos(q(2)) -...
          1)))/2 + ((cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)))*(cos(q(1))*sin(q(2)) + 2*cos(q(2))*sin(q(1)) -...
          sin(q(1))*(cos(q(2)) - 1)))/2 + ((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(sin(q(1))*sin(q(2)) - 2*...
         cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - (sin(q(1))*(cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) +...
          cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 + (cos(q(1))*...
         (sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) +...
          sin(q(1))*(cos(q(2)) - 1)))/2) - dq(3)*((sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*...
         (cos(q(2)) - 1))*(cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) + cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*...
         sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)) - (cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*...
         (cos(q(2)) - 1))*(sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*...
         sin(q(1)) + sin(q(1))*(cos(q(2)) - 1))) + dq(2)*((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(cos(q(1)) - 2*...
         cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)) - (cos(q(1) + q(2) + q(3)) + cos(q(1) +...
          q(2)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)));
  C(3,1)=- dq(2)*(((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)))*(cos(q(1)) - 2*...
         cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - ((cos(q(1) + q(2) + q(3)) +...
          cos(q(1) + q(2)) + cos(q(1)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*...
         (cos(q(2)) - 1)))/2 + ((cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)))*(cos(q(1))*sin(q(2)) + 2*cos(q(2))*...
         sin(q(1)) - sin(q(1))*(cos(q(2)) - 1)))/2 + ((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(sin(q(1))*...
         sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - (sin(q(1))*(cos(q(1) + q(2) + q(3)) +...
          cos(q(1) + q(2)) + cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 +...
          (cos(q(1))*(sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*...
         sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)))/2) - dq(1)*((cos(q(1))*sin(q(2)) + 2*cos(q(2))*sin(q(1)) - sin(q(1))*...
         (cos(q(2)) - 1))*(cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)) + cos(q(1))) + (sin(q(1) + q(2) + q(3)) +...
          sin(q(1) + q(2)) + sin(q(1)))*(sin(q(1))*sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)));
  C(3,2)=- dq(1)*(((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)))*(cos(q(1)) - 2*...
         cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - ((cos(q(1) + q(2) + q(3)) +...
          cos(q(1) + q(2)) + cos(q(1)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*...
         (cos(q(2)) - 1)))/2 + ((cos(q(1) + q(2) + q(3)) + cos(q(1) + q(2)))*(cos(q(1))*sin(q(2)) + 2*cos(q(2))*...
         sin(q(1)) - sin(q(1))*(cos(q(2)) - 1)))/2 + ((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(sin(q(1))*...
         sin(q(2)) - 2*cos(q(1))*cos(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 - (sin(q(1))*(cos(q(1) + q(2) + q(3)) +...
          cos(q(1) + q(2)) + cos(q(1)) - 2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)))/2 +...
          (cos(q(1))*(sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)) + sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*...
         sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)))/2) - dq(2)*((sin(q(1) + q(2) + q(3)) + sin(q(1) + q(2)))*(cos(q(1)) -...
          2*cos(q(1))*cos(q(2)) + sin(q(1))*sin(q(2)) + cos(q(1))*(cos(q(2)) - 1)) - (cos(q(1) + q(2) + q(3)) +...
          cos(q(1) + q(2)))*(sin(q(1)) - cos(q(1))*sin(q(2)) - 2*cos(q(2))*sin(q(1)) + sin(q(1))*(cos(q(2)) - 1)));
  C(3,3)=0;

 