function [djac] = out_djac8(q,dq)

  djac(1,1)=0;
  djac(1,2)=0;
  djac(1,3)=0;
  djac(1,4)=0;
  djac(1,5)=dq(6)*(sin(q(4))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) -...
          cos(q(4))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))))) + dq(8)*(cos(q(4))*(sin(q(8))*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) +...
          cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))))) - sin(q(4))*(sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6)))))) - dq(7)*(cos(q(4))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) - sin(q(4))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6)))))) + dq(4)*(sin(q(4))*(sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - cos(q(4))*(q(3) + sin(q(8))*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) -...
          2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*...
         cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))))) + sin(q(4))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) + q(3)*...
         cos(q(4)) - q(2)*sin(q(4)) + cos(q(4))*(sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))))) - dq(5)*...
         (sin(q(4))*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6)))*(2*cos(q(8)) -...
          2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) - cos(q(5))*sin(q(4))*sin(q(6))*sin(q(7))) - 3*...
         cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6))) + cos(q(5))*...
         sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7))) + cos(q(4))*((2*cos(q(8)) - 2)*...
         (cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*...
         cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(4))*cos(q(5))*sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*...
         cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) + cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) -...
          1) + cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7))));
  djac(1,6)=dq(5)*(sin(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) - cos(q(4))*sin(q(5))*(q(3) +...
          sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*...
         cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) -...
          3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) + sin(q(4))*sin(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) -...
          (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) +...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))))) - cos(q(5))*sin(q(4))*((2*cos(q(8)) - 2)*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*...
         cos(q(5))*cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(4))*cos(q(5))*...
         sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*...
         sin(q(6))) + cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7))) +...
          cos(q(4))*cos(q(5))*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6)))*(2*...
         cos(q(8)) - 2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) - cos(q(5))*sin(q(4))*sin(q(6))*...
         sin(q(7))) - 3*cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6))) +...
          cos(q(5))*sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)))) - dq(7)*(cos(q(4))*...
         cos(q(5))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) +...
          (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) + cos(q(5))*sin(q(4))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6)))))) - dq(4)*(cos(q(4))*cos(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) -...
          cos(q(5))*(q(2)*cos(q(4)) + q(3)*sin(q(4))) + cos(q(5))*sin(q(4))*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))))) + cos(q(4))*cos(q(5))*(sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - cos(q(5))*sin(q(4))*(sin(q(8))*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) -...
          2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*...
         cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5)))))) - dq(6)*(cos(q(4))*cos(q(5))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))))) + cos(q(5))*sin(q(4))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) -...
          sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))))) + dq(8)*(cos(q(4))*cos(q(5))*...
         (sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) + cos(q(5))*sin(q(4))*(sin(q(8))*(cos(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5)))) + cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))));
  djac(1,7)=dq(8)*(cos(q(4))*cos(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + cos(q(8))*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))))) + cos(q(5))*sin(q(4))*(sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6)))))) - dq(5)*(cos(q(6))*sin(q(5)) - sin(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(4))*sin(q(5))*...
         (q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - sin(q(4))*sin(q(5))*(q(2) - sin(q(8))*(cos(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))) + sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))))) + cos(q(5))*sin(q(4))*((2*cos(q(8)) - 2)*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(4))*...
         cos(q(5))*sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*...
         cos(q(7))*sin(q(6))) + cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(4))*cos(q(5))*cos(q(6))*...
         sin(q(7))) - cos(q(4))*cos(q(5))*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*...
         sin(q(6)))*(2*cos(q(8)) - 2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) - cos(q(5))*sin(q(4))*...
         sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*...
         sin(q(6))) + cos(q(5))*sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)))) - dq(4)*...
         (cos(q(4))*cos(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - cos(q(5))*(q(2)*cos(q(4)) +...
          q(3)*sin(q(4))) + cos(q(5))*sin(q(4))*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) +...
          cos(q(4))*cos(q(5))*(sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - cos(q(5))*sin(q(4))*(sin(q(8))*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*...
         (cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*...
         (cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5)))))) - dq(6)*(cos(q(5))*sin(q(6)) + cos(q(4))*cos(q(5))*((cos(q(7)) - 1)*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))))) + cos(q(5))*sin(q(4))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) -...
          sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))))) - dq(7)*(cos(q(4))*cos(q(5))*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*...
         cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) + cos(q(5))*sin(q(4))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))));
  djac(1,8)=dq(5)*(sin(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + sin(q(5))*sin(q(6))*sin(q(7)) +...
          cos(q(6))*sin(q(5))*(cos(q(7)) - 1) - cos(q(4))*sin(q(5))*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))))) + sin(q(4))*sin(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) -...
          cos(q(5))*sin(q(4))*((2*cos(q(8)) - 2)*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*...
         cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(4))*cos(q(5))*sin(q(6))*...
         sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) +...
          cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7))) + cos(q(4))*...
         cos(q(5))*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6)))*(2*cos(q(8)) -...
          2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) - cos(q(5))*sin(q(4))*sin(q(6))*sin(q(7))) - 3*...
         cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6))) + cos(q(5))*...
         sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7))) - 2*cos(q(6))*cos(q(7))*...
         sin(q(5))) - dq(4)*(cos(q(4))*cos(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) -...
          cos(q(5))*(q(2)*cos(q(4)) + q(3)*sin(q(4))) + cos(q(5))*sin(q(4))*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))))) + cos(q(4))*cos(q(5))*(sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - cos(q(5))*sin(q(4))*(sin(q(8))*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) -...
          2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*...
         cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5)))))) - dq(7)*(cos(q(4))*cos(q(5))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) +...
          cos(q(5))*sin(q(4))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) + cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6))) + dq(8)*(cos(q(4))*cos(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))))) + cos(q(5))*sin(q(4))*(sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))))) - dq(6)*...
         (cos(q(4))*cos(q(5))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*...
         (cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) - cos(q(5))*sin(q(6))*(cos(q(7)) - 1) +...
          cos(q(5))*sin(q(4))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) + cos(q(5))*cos(q(6))*sin(q(7)) + 2*...
         cos(q(5))*cos(q(7))*sin(q(6)));
  djac(1,9)=0;
  djac(1,10)=0;
  djac(2,1)=0;
  djac(2,2)=0;
  djac(2,3)=0;
  djac(2,4)=dq(7)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*...
         (cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) - dq(8)*(sin(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) +...
          cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))))) + dq(4)*(sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) + dq(6)*...
         ((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) +...
          (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) - dq(5)*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6)))*(2*cos(q(8)) - 2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*...
         sin(q(4)) - cos(q(5))*sin(q(4))*sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6))) + cos(q(5))*sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*...
         cos(q(6))*sin(q(4))*sin(q(7)));
  djac(2,5)=- dq(4)*(sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(7))) - q(1)*sin(q(4))) - dq(6)*cos(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*sin(q(6))*sin(q(7))) - dq(8)*...
         cos(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*...
         sin(q(6))*sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))) - dq(5)*...
         cos(q(4))*((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) +...
          q(7) + q(8))*sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*sin(q(5))) +...
          sin(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) - dq(7)*cos(q(4))*(3*cos(q(6) + q(7) +...
          q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*...
         sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) +...
          cos(q(5))*sin(q(6))*sin(q(7)));
  djac(2,6)=dq(5)*(sin(q(5))*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(4))*sin(q(6)))*(2*cos(q(8)) - 2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) - cos(q(5))*...
         sin(q(4))*sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(4))*sin(q(6))) + cos(q(5))*sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(4))*...
         sin(q(7))) + cos(q(5))*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - q(3)*cos(q(5)) - cos(q(5))*...
         sin(q(4))*((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) +...
          q(7) + q(8))*sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*sin(q(5))) +...
          sin(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) - sin(q(4))*sin(q(5))*(q(1) + (cos(q(5))*...
         cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) +...
          2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*...
         (cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) + q(1)*sin(q(4))*sin(q(5))) - dq(7)*(sin(q(5))*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))))) + cos(q(5))*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7)))) + dq(8)*...
         (sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) - cos(q(5))*sin(q(4))*(3*...
         cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*...
         sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))))) - dq(4)*(sin(q(5))*...
         (sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + (2*...
         cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) -...
          3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - cos(q(4))*cos(q(5))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*...
         (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) +...
          cos(q(5))*cos(q(6))*sin(q(7))) + q(1)*cos(q(4))*cos(q(5))) - dq(6)*(sin(q(5))*((cos(q(7)) - 1)*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))))) + cos(q(5))*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) -...
          cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*...
         cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*sin(q(6))*sin(q(7))));
  djac(2,7)=dq(5)*(sin(q(5))*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(4))*sin(q(6)))*(2*cos(q(8)) - 2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) - cos(q(5))*...
         sin(q(4))*sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(4))*sin(q(6))) + cos(q(5))*sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(4))*...
         sin(q(7))) + cos(q(5))*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - q(3)*cos(q(5)) - cos(q(5))*...
         sin(q(4))*((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) +...
          q(7) + q(8))*sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*sin(q(5))) +...
          sin(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) - sin(q(4))*sin(q(5))*(q(1) + (cos(q(5))*...
         cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) +...
          2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*...
         (cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) + q(1)*sin(q(4))*sin(q(5)) + cos(q(4))*cos(q(5))*cos(q(6))) -...
          dq(7)*(sin(q(5))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) + cos(q(5))*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*...
         cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*...
         (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(5))*...
         sin(q(6))*sin(q(7)))) + dq(8)*(sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))))) - cos(q(5))*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6))))) - dq(4)*(sin(q(5))*(sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - cos(q(4))*sin(q(6)) -...
          cos(q(4))*cos(q(5))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) -...
          2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*...
         sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) + q(1)*cos(q(4))*...
         cos(q(5)) + cos(q(6))*sin(q(4))*sin(q(5))) - dq(6)*(sin(q(5))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))))) - cos(q(6))*sin(q(4)) + cos(q(5))*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*...
         cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*sin(q(6))*...
         sin(q(7))) + cos(q(4))*sin(q(5))*sin(q(6)));
  djac(2,8)=dq(8)*(sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))))) - cos(q(5))*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6))))) - dq(6)*((cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + sin(q(5))*...
         ((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) +...
          (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) - 2*cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) + sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + cos(q(5))*sin(q(4))*...
         (3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*...
         (2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) -...
          cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*sin(q(6))*sin(q(7)))) - dq(4)*((cos(q(7)) - 1)*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(5))*(sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - 2*...
         cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - cos(q(4))*cos(q(5))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(7))) + q(1)*cos(q(4))*cos(q(5))) - dq(7)*(sin(q(5))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))))) -...
          cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + cos(q(5))*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7)))) - dq(5)*...
         (q(3)*cos(q(5)) - cos(q(5))*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) -...
          sin(q(5))*((cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6)))*(2*cos(q(8)) -...
          2) - sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) - cos(q(5))*sin(q(4))*sin(q(6))*sin(q(7))) - 3*...
         cos(q(8))*(cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(4))*sin(q(6))) + cos(q(5))*...
         sin(q(4))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(4))*sin(q(7))) + cos(q(5))*sin(q(4))*...
         ((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*...
         sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*sin(q(5))) + sin(q(5))*sin(q(6))*...
         (cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) + sin(q(4))*sin(q(5))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*...
         (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) +...
          cos(q(5))*cos(q(6))*sin(q(7))) - q(1)*sin(q(4))*sin(q(5)) + cos(q(4))*cos(q(5))*cos(q(6))*(cos(q(7)) - 1) - 2*...
         cos(q(4))*cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(4))*cos(q(5))*sin(q(6))*sin(q(7)));
  djac(2,9)=0;
  djac(2,10)=0;
  djac(3,1)=0;
  djac(3,2)=0;
  djac(3,3)=0;
  djac(3,4)=dq(5)*((2*cos(q(8)) - 2)*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*...
         cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(4))*cos(q(5))*sin(q(6))*...
         sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) +...
          cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7))) - dq(8)*(sin(q(8))*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) + dq(7)*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))))) - dq(4)*(sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) + dq(6)*((cos(q(7)) - 1)*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))));
  djac(3,5)=dq(4)*(cos(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(7))) - q(1)*cos(q(4))) - dq(6)*sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*sin(q(6))*sin(q(7))) - dq(8)*...
         sin(q(4))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*...
         sin(q(6))*sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))) - dq(5)*...
         sin(q(4))*((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) +...
          q(7) + q(8))*sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*sin(q(5))) +...
          sin(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) - dq(7)*sin(q(4))*(3*cos(q(6) + q(7) +...
          q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*...
         sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) +...
          cos(q(5))*sin(q(6))*sin(q(7)));
  djac(3,6)=dq(8)*(sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))))) + cos(q(4))*cos(q(5))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6))))) - dq(7)*(sin(q(5))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) - cos(q(4))*cos(q(5))*(3*cos(q(6) + q(7) +...
          q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*...
         sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) +...
          cos(q(5))*sin(q(6))*sin(q(7)))) - dq(5)*(cos(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) -...
          (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) +...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))))) + sin(q(5))*((2*cos(q(8)) - 2)*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*...
         cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(4))*cos(q(5))*sin(q(6))*...
         sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) +...
          cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7))) - q(2)*cos(q(5)) -...
          cos(q(4))*cos(q(5))*((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*...
         sin(q(6) + q(7) + q(8))*sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*...
         sin(q(5))) + sin(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) - cos(q(4))*sin(q(5))*(q(1) +...
          (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*...
         cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*...
         (cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) + q(1)*cos(q(4))*sin(q(5))) - dq(6)*(sin(q(5))*((cos(q(7)) -...
          1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + (2*...
         cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) - cos(q(4))*cos(q(5))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) -...
          (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*...
         cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*...
         sin(q(6))*sin(q(7)))) + dq(4)*(sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) +...
          cos(q(5))*sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) -...
          2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*...
         sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) - q(1)*cos(q(5))*sin(q(4)));
  djac(3,7)=dq(8)*(sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))))) + cos(q(4))*cos(q(5))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6))))) - dq(7)*(sin(q(5))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) - cos(q(4))*cos(q(5))*(3*cos(q(6) + q(7) +...
          q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*...
         sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) +...
          cos(q(5))*sin(q(6))*sin(q(7)))) + dq(5)*(q(2)*cos(q(5)) - sin(q(5))*((2*cos(q(8)) - 2)*(cos(q(4))*cos(q(5))*...
         cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(4))*cos(q(5))*sin(q(6))*sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) +...
          cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) + cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(4))*...
         cos(q(5))*cos(q(6))*sin(q(7))) - cos(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) +...
          cos(q(4))*cos(q(5))*((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*...
         sin(q(6) + q(7) + q(8))*sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*...
         sin(q(5))) + sin(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) + cos(q(4))*sin(q(5))*(q(1) +...
          (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*...
         cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*...
         (cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) - q(1)*cos(q(4))*sin(q(5)) + cos(q(5))*cos(q(6))*sin(q(4))) -...
          dq(6)*(cos(q(4))*cos(q(6)) + sin(q(5))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) +...
          sin(q(4))*sin(q(5))*sin(q(6)) - cos(q(4))*cos(q(5))*(3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*...
         cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*sin(q(6))*...
         sin(q(7)))) + dq(4)*(sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) + sin(q(4))*sin(q(6)) +...
          cos(q(5))*sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) -...
          2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*...
         sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) - q(1)*cos(q(5))*...
         sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5)));
  djac(3,8)=dq(6)*((cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(5))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) - 2*cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) + sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + cos(q(4))*cos(q(5))*...
         (3*cos(q(6) + q(7) + q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*...
         (2*cos(q(8)) - 2) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) -...
          cos(q(5))*cos(q(6))*(cos(q(7)) - 1) + cos(q(5))*sin(q(6))*sin(q(7)))) + dq(4)*(sin(q(5))*(sin(q(8))*...
         (cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) -...
          2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*...
         cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))))) - (cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 2*...
         cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) + cos(q(5))*sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(7))) - q(1)*cos(q(5))*sin(q(4))) - dq(5)*(cos(q(5))*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) -...
          (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) +...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))))) + sin(q(5))*((2*cos(q(8)) - 2)*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*...
         cos(q(7))*sin(q(6))) - sin(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(4))*cos(q(5))*sin(q(6))*...
         sin(q(7))) - 3*cos(q(8))*(cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(4))*cos(q(5))*cos(q(7))*sin(q(6))) +...
          cos(q(4))*cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(4))*cos(q(5))*cos(q(6))*sin(q(7))) - q(2)*cos(q(5)) -...
          cos(q(4))*cos(q(5))*((cos(q(6))*sin(q(5))*sin(q(7)) + cos(q(7))*sin(q(5))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*...
         sin(q(6) + q(7) + q(8))*sin(q(5)) - 2*sin(q(8))*(sin(q(5))*sin(q(6))*sin(q(7)) - cos(q(6))*cos(q(7))*...
         sin(q(5))) + sin(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(6))*sin(q(5))*sin(q(7))) - cos(q(4))*sin(q(5))*(q(1) +...
          (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*...
         cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*...
         (cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7))) + q(1)*cos(q(4))*sin(q(5)) + cos(q(5))*cos(q(6))*sin(q(4))*...
         (cos(q(7)) - 1) - 2*cos(q(5))*cos(q(6))*cos(q(7))*sin(q(4)) + cos(q(5))*sin(q(4))*sin(q(6))*sin(q(7))) + dq(8)*...
         (sin(q(5))*(sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) + cos(q(4))*cos(q(5))*(3*...
         cos(q(6) + q(7) + q(8))*cos(q(5)) - 2*cos(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*...
         sin(q(7))) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))))) - dq(7)*(cos(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + sin(q(5))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) - sin(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + (2*cos(q(8)) - 2)*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - 3*cos(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - cos(q(4))*cos(q(5))*(3*cos(q(6) + q(7) +...
          q(8))*cos(q(5)) - (cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7)))*(2*cos(q(8)) - 2) + 2*...
         sin(q(8))*(cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6))) - cos(q(5))*cos(q(6))*cos(q(7)) +...
          cos(q(5))*sin(q(6))*sin(q(7))));
  djac(3,9)=0;
  djac(3,10)=0;

 