function [p] = out_p8(q)

  p(1,1)=q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*cos(q(8)) - 2) -...
          3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*...
         sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7));
  p(2,1)=q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))));
  p(3,1)=q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))));
  p(4,1)=1;

 