function [p] = out_p10(q)

  p(1,1)=q(1) + (cos(q(5))*cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*sin(q(6)))*(2*cos(q(10)) - 2) -...
          3*sin(q(6) + q(9) + q(10))*cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*cos(q(9)) - cos(q(5))*...
         sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*(cos(q(9)) - 1) + cos(q(5))*cos(q(6))*sin(q(9));
  p(2,1)=q(2) - sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(9)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(9))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))));
  p(3,1)=q(3) + sin(q(10))*(cos(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(10))*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))));
  p(4,1)=1;

 