function [dp] = out_dp10(q,dq)

  dp(1,1)=dq(1) - dq(5)*(cos(q(4))*(q(2) - sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + sin(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(9)) - 1)*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(9))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) +...
          sin(q(4))*(q(3) + sin(q(10))*(cos(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(9))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) - 3*cos(q(10))*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - q(2)*cos(q(4)) - q(3)*sin(q(4))) - dq(6)*...
         (cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) - cos(q(4))*cos(q(5))*(q(3) + sin(q(10))*(cos(q(9))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*(cos(q(9))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(10))*(cos(q(9))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))))) + cos(q(5))*sin(q(4))*(q(2) - sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(9)) - 1)*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(9))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))))) + dq(9)*...
         (cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(4))*cos(q(5))*(q(3) + sin(q(10))*...
         (cos(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6)))) + (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*...
         cos(q(10)) - 2)*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) -...
          3*cos(q(10))*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - cos(q(5))*sin(q(4))*(q(2) - sin(q(10))*(cos(q(9))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) -...
          (cos(q(9)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(10)) - 2)*(cos(q(9))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5)))) + sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(10))*(cos(q(9))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5)))))) - dq(10)*(cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(9)) - 1) -...
          cos(q(4))*cos(q(5))*(q(3) + sin(q(10))*(cos(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(10))*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) + cos(q(5))*sin(q(4))*(q(2) -...
          sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(9))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(9)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*...
         cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - 2*cos(q(5))*cos(q(6))*cos(q(9)) + cos(q(5))*sin(q(6))*sin(q(9)));
  dp(2,1)=dq(2) + dq(6)*(sin(q(5))*(q(3) + sin(q(10))*(cos(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) + sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(9)) - 1)*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(9))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(10))*(cos(q(9))*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - q(3)*...
         sin(q(5)) + cos(q(5))*sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*sin(q(6)))*(2*...
         cos(q(10)) - 2) - 3*sin(q(6) + q(9) + q(10))*cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*cos(q(9)) -...
          cos(q(5))*sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*(cos(q(9)) - 1) + cos(q(5))*cos(q(6))*sin(q(9))) - q(1)*...
         cos(q(5))*sin(q(4))) + dq(5)*(cos(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*...
         sin(q(6)))*(2*cos(q(10)) - 2) - 3*sin(q(6) + q(9) + q(10))*cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*...
         cos(q(9)) - cos(q(5))*sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*(cos(q(9)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(9))) - q(1)*cos(q(4))) + dq(9)*(sin(q(4))*sin(q(6)) + sin(q(5))*(q(3) + sin(q(10))*(cos(q(9))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*(cos(q(9))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(10))*(cos(q(9))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))))) - q(3)*sin(q(5)) + cos(q(5))*sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*...
         sin(q(6)))*(2*cos(q(10)) - 2) - 3*sin(q(6) + q(9) + q(10))*cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*...
         cos(q(9)) - cos(q(5))*sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*(cos(q(9)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(9))) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5))) + dq(10)*(sin(q(5))*(q(3) + sin(q(10))*...
         (cos(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*...
         sin(q(5))*sin(q(6)))) + (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*...
         cos(q(10)) - 2)*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) -...
          3*cos(q(10))*(cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - (cos(q(9)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + 2*cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - q(3)*sin(q(5)) + sin(q(9))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + cos(q(5))*sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*...
         sin(q(9)) + cos(q(5))*cos(q(9))*sin(q(6)))*(2*cos(q(10)) - 2) - 3*sin(q(6) + q(9) + q(10))*cos(q(5)) + 2*...
         sin(q(10))*(cos(q(5))*cos(q(6))*cos(q(9)) - cos(q(5))*sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*(cos(q(9)) -...
          1) + cos(q(5))*cos(q(6))*sin(q(9))) - q(1)*cos(q(5))*sin(q(4))) - dq(4)*(sin(q(10))*(cos(q(9))*...
         (cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6)))) + (cos(q(9)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*...
         (cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5)))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(10))*...
         (cos(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5)))));
  dp(3,1)=dq(3) + dq(5)*(sin(q(4))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*...
         sin(q(6)))*(2*cos(q(10)) - 2) - 3*sin(q(6) + q(9) + q(10))*cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*...
         cos(q(9)) - cos(q(5))*sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*(cos(q(9)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(9))) - q(1)*sin(q(4))) - dq(10)*(sin(q(5))*(q(2) - sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + sin(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(9)) - 1)*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(9))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) -...
          (cos(q(9)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + 2*cos(q(9))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - q(2)*sin(q(5)) + sin(q(9))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) + cos(q(4))*cos(q(5))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*sin(q(6)))*(2*...
         cos(q(10)) - 2) - 3*sin(q(6) + q(9) + q(10))*cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*cos(q(9)) -...
          cos(q(5))*sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*(cos(q(9)) - 1) + cos(q(5))*cos(q(6))*sin(q(9))) - q(1)*...
         cos(q(4))*cos(q(5))) - dq(4)*(sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          sin(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(9)) - 1)*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) - sin(q(9))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - 3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - dq(6)*(sin(q(5))*(q(2) -...
          sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(9))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(9)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*...
         cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) +...
          3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(9))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - q(2)*sin(q(5)) + cos(q(4))*cos(q(5))*(q(1) + (cos(q(5))*...
         cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*sin(q(6)))*(2*cos(q(10)) - 2) - 3*sin(q(6) + q(9) + q(10))*...
         cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*cos(q(9)) - cos(q(5))*sin(q(6))*sin(q(9))) + cos(q(5))*sin(q(6))*...
         (cos(q(9)) - 1) + cos(q(5))*cos(q(6))*sin(q(9))) - q(1)*cos(q(4))*cos(q(5))) - dq(9)*(cos(q(4))*sin(q(6)) +...
          sin(q(5))*(q(2) - sin(q(10))*(cos(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(9))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(9)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - (2*cos(q(10)) - 2)*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + 3*cos(q(10))*(cos(q(9))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) -...
          sin(q(9))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - q(2)*sin(q(5)) + cos(q(4))*cos(q(5))*...
         (q(1) + (cos(q(5))*cos(q(6))*sin(q(9)) + cos(q(5))*cos(q(9))*sin(q(6)))*(2*cos(q(10)) - 2) - 3*sin(q(6) +...
          q(9) + q(10))*cos(q(5)) + 2*sin(q(10))*(cos(q(5))*cos(q(6))*cos(q(9)) - cos(q(5))*sin(q(6))*sin(q(9))) +...
          cos(q(5))*sin(q(6))*(cos(q(9)) - 1) + cos(q(5))*cos(q(6))*sin(q(9))) - q(1)*cos(q(4))*cos(q(5)) - cos(q(6))*...
         sin(q(4))*sin(q(5)));

 