function [djac_dq] = out_djac_dq8(q,dq)

  djac_dq(1,1)=dq(5)^2*(q(1)*cos(q(4))^2 + q(1)*sin(q(4))^2) - (q(2) - sin(q(8))*(cos(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*...
         sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))) + sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*...
         (cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*...
         cos(q(6))*sin(q(5)))))*(dq(6)^2*cos(q(4))*cos(q(5))*sin(q(5)) - dq(4)*dq(5)*sin(q(4)) + dq(7)^2*cos(q(4))*...
         cos(q(5))*sin(q(5)) + dq(8)^2*cos(q(4))*cos(q(5))*sin(q(5)) + dq(4)*dq(6)*cos(q(4))*cos(q(5)) + dq(4)*dq(7)*...
         cos(q(4))*cos(q(5)) + dq(4)*dq(8)*cos(q(4))*cos(q(5)) - dq(5)*dq(6)*sin(q(4))*sin(q(5)) - dq(5)*dq(7)*...
         sin(q(4))*sin(q(5)) - dq(5)*dq(8)*sin(q(4))*sin(q(5))) - (q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))))*...
         (dq(4)*dq(5)*cos(q(4)) + dq(6)^2*cos(q(5))*sin(q(4))*sin(q(5)) + dq(7)^2*cos(q(5))*sin(q(4))*sin(q(5)) +...
          dq(8)^2*cos(q(5))*sin(q(4))*sin(q(5)) + dq(4)*dq(6)*cos(q(5))*sin(q(4)) + dq(4)*dq(7)*cos(q(5))*sin(q(4)) +...
          dq(5)*dq(6)*cos(q(4))*sin(q(5)) + dq(4)*dq(8)*cos(q(5))*sin(q(4)) + dq(5)*dq(7)*cos(q(4))*sin(q(5)) +...
          dq(5)*dq(8)*cos(q(4))*sin(q(5))) - (dq(6)^2*(cos(q(4))^2*cos(q(5))^2 + cos(q(5))^2*sin(q(4))^2) + dq(7)^2*...
         (cos(q(4))^2*cos(q(5))^2 + cos(q(5))^2*sin(q(4))^2) + dq(8)^2*(cos(q(4))^2*cos(q(5))^2 + cos(q(5))^2*...
         sin(q(4))^2) + dq(5)^2*(cos(q(4))^2 + sin(q(4))^2))*(q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(7))) + dq(8)^2*(cos(q(5))*sin(q(4))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) - 2*cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + q(3)*sin(q(5)) - sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(5))*sin(q(4))) + cos(q(4))*cos(q(5))*...
         ((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) + q(2)*sin(q(5)) - sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) + q(1)*cos(q(4))*cos(q(5)))) + dq(6)^2*(cos(q(4))*cos(q(5))*(q(2)*sin(q(5)) + q(1)*cos(q(4))*...
         cos(q(5))) + cos(q(5))*sin(q(4))*(q(3)*sin(q(5)) + q(1)*cos(q(5))*sin(q(4)))) + dq(7)^2*(cos(q(4))*cos(q(5))*...
         (q(2)*sin(q(5)) - cos(q(4))*sin(q(6)) + q(1)*cos(q(4))*cos(q(5)) + cos(q(6))*sin(q(4))*sin(q(5))) -...
          cos(q(5))*sin(q(4))*(sin(q(4))*sin(q(6)) - q(3)*sin(q(5)) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*cos(q(6))*...
         sin(q(5)))) + dq(3)*dq(5)*sin(q(4)) + dq(7)*dq(8)*(cos(q(5))*sin(q(4))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - 2*cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + q(3)*...
         sin(q(5)) - sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(5))*sin(q(4))) -...
          cos(q(4))*cos(q(5))*(q(2)*sin(q(5)) - cos(q(4))*sin(q(6)) + q(1)*cos(q(4))*cos(q(5)) + cos(q(6))*sin(q(4))*...
         sin(q(5))) + cos(q(5))*sin(q(4))*(sin(q(4))*sin(q(6)) - q(3)*sin(q(5)) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*...
         cos(q(6))*sin(q(5))) + cos(q(4))*cos(q(5))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + q(2)*sin(q(5)) - sin(q(7))*...
         (cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(4))*cos(q(5)))) - dq(5)*dq(6)*(sin(q(4))*...
         (q(2)*sin(q(5)) + q(1)*cos(q(4))*cos(q(5))) - cos(q(4))*(q(3)*sin(q(5)) + q(1)*cos(q(5))*sin(q(4)))) -...
          dq(6)*dq(7)*(cos(q(4))*cos(q(5))*(q(2)*sin(q(5)) + q(1)*cos(q(4))*cos(q(5))) - cos(q(4))*cos(q(5))*(q(2)*...
         sin(q(5)) - cos(q(4))*sin(q(6)) + q(1)*cos(q(4))*cos(q(5)) + cos(q(6))*sin(q(4))*sin(q(5))) + cos(q(5))*...
         sin(q(4))*(q(3)*sin(q(5)) + q(1)*cos(q(5))*sin(q(4))) + cos(q(5))*sin(q(4))*(sin(q(4))*sin(q(6)) - q(3)*...
         sin(q(5)) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5)))) - dq(5)*dq(7)*(sin(q(4))*(q(2)*...
         sin(q(5)) - cos(q(4))*sin(q(6)) + q(1)*cos(q(4))*cos(q(5)) + cos(q(6))*sin(q(4))*sin(q(5))) + cos(q(4))*...
         (sin(q(4))*sin(q(6)) - q(3)*sin(q(5)) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5)))) + dq(4)*...
         dq(6)*(q(2)*cos(q(4))*cos(q(5)) + q(3)*cos(q(5))*sin(q(4))) + dq(4)*dq(7)*(q(2)*cos(q(4))*cos(q(5)) +...
          q(3)*cos(q(5))*sin(q(4))) + dq(4)*dq(8)*(q(2)*cos(q(4))*cos(q(5)) + q(3)*cos(q(5))*sin(q(4))) + dq(4)*...
         dq(5)*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + dq(6)*dq(8)*(cos(q(5))*sin(q(4))*((cos(q(7)) - 1)*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - 2*cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + q(3)*sin(q(5)) - sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(5))*...
         sin(q(4))) - cos(q(4))*cos(q(5))*(q(2)*sin(q(5)) + q(1)*cos(q(4))*cos(q(5))) - cos(q(5))*sin(q(4))*(q(3)*...
         sin(q(5)) + q(1)*cos(q(5))*sin(q(4))) + cos(q(4))*cos(q(5))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + q(2)*sin(q(5)) -...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(4))*cos(q(5)))) + dq(5)*dq(8)*...
         (cos(q(4))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - 2*cos(q(7))*(sin(q(4))*...
         sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + q(3)*sin(q(5)) - sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) + q(1)*cos(q(5))*sin(q(4))) - sin(q(4))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + q(2)*...
         sin(q(5)) - sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(4))*cos(q(5)))) +...
          dq(2)*dq(5)*cos(q(4)) - dq(3)*dq(6)*cos(q(4))*cos(q(5)) - dq(3)*dq(7)*cos(q(4))*cos(q(5)) - dq(3)*dq(8)*...
         cos(q(4))*cos(q(5)) + dq(2)*dq(6)*cos(q(5))*sin(q(4)) + dq(2)*dq(7)*cos(q(5))*sin(q(4)) + dq(2)*dq(8)*...
         cos(q(5))*sin(q(4));
  djac_dq(2,1)=dq(3)*dq(4) - (q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*...
         sin(q(6)))*(2*cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*...
         cos(q(7)) - cos(q(5))*sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*...
         sin(q(7)))*(dq(4)*dq(5)*sin(q(4)) + dq(6)^2*cos(q(4))*cos(q(5))*sin(q(5)) + dq(7)^2*cos(q(4))*cos(q(5))*...
         sin(q(5)) + dq(8)^2*cos(q(4))*cos(q(5))*sin(q(5)) - dq(4)*dq(6)*cos(q(4))*cos(q(5)) - dq(4)*dq(7)*cos(q(4))*...
         cos(q(5)) - dq(4)*dq(8)*cos(q(4))*cos(q(5)) + dq(5)*dq(6)*sin(q(4))*sin(q(5)) + dq(5)*dq(7)*sin(q(4))*...
         sin(q(5)) + dq(5)*dq(8)*sin(q(4))*sin(q(5))) + dq(8)^2*(sin(q(5))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + q(2)*...
         sin(q(5)) - sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(4))*cos(q(5))) -...
          cos(q(5))*sin(q(4))*(cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(7)) - 1) - 2*...
         cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7)))) + (q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) +...
          (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) -...
          sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*...
         cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))))*...
         (dq(5)*dq(6)*(cos(q(4))^2*cos(q(5)) + cos(q(5))*sin(q(4))^2) + dq(5)*dq(7)*(cos(q(4))^2*cos(q(5)) +...
          cos(q(5))*sin(q(4))^2) + dq(5)*dq(8)*(cos(q(4))^2*cos(q(5)) + cos(q(5))*sin(q(4))^2) - dq(5)^2*cos(q(4))*...
         sin(q(4)) + dq(6)^2*cos(q(4))*cos(q(5))^2*sin(q(4)) + dq(7)^2*cos(q(4))*cos(q(5))^2*sin(q(4)) + dq(8)^2*...
         cos(q(4))*cos(q(5))^2*sin(q(4))) + dq(6)^2*(sin(q(5))*(q(2)*sin(q(5)) + q(1)*cos(q(4))*cos(q(5))) -...
          cos(q(5))^2*sin(q(4))*(q(3)*cos(q(4)) - q(2)*sin(q(4)))) + dq(4)^2*q(2) + dq(7)^2*(sin(q(5))*(q(2)*sin(q(5)) -...
          cos(q(4))*sin(q(6)) + q(1)*cos(q(4))*cos(q(5)) + cos(q(6))*sin(q(4))*sin(q(5))) + cos(q(5))*sin(q(4))*...
         (cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))))) - (dq(5)^2*cos(q(4))^2 + dq(6)^2*...
         (sin(q(5))^2 + cos(q(5))^2*sin(q(4))^2) + dq(7)^2*(sin(q(5))^2 + cos(q(5))^2*sin(q(4))^2) + dq(8)^2*(sin(q(5))^2 +...
          cos(q(5))^2*sin(q(4))^2) + dq(4)^2)*(q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) - (cos(q(7)) - 1)*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*...
         sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) + sin(q(7))*...
         (sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*sin(q(4)) -...
          cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))))) - dq(3)*...
         dq(6)*sin(q(5)) - dq(3)*dq(7)*sin(q(5)) - dq(3)*dq(8)*sin(q(5)) - dq(4)*dq(7)*(q(1)*cos(q(4))*cos(q(5)) -...
          cos(q(4))*sin(q(6)) + cos(q(6))*sin(q(4))*sin(q(5))) + dq(6)*dq(8)*(sin(q(5))*((cos(q(7)) - 1)*(cos(q(4))*...
         sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*...
         sin(q(5))) + q(2)*sin(q(5)) - sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(4))*...
         cos(q(5))) - sin(q(5))*(q(2)*sin(q(5)) + q(1)*cos(q(4))*cos(q(5))) + cos(q(5))^2*sin(q(4))*(q(3)*cos(q(4)) -...
          q(2)*sin(q(4))) - cos(q(5))*sin(q(4))*(cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*...
         (cos(q(7)) - 1) - 2*cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7)))) - dq(4)*dq(8)*((cos(q(7)) -...
          1)*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + q(1)*...
         cos(q(4))*cos(q(5))) + dq(5)*dq(7)*(cos(q(4))*(cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*...
         sin(q(4)))) + q(1)*sin(q(4))*sin(q(5)) - cos(q(5))*sin(q(4))*(q(2)*cos(q(4)) + q(3)*sin(q(4)))) - dq(5)*dq(8)*...
         (cos(q(4))*(cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(7)) - 1) - 2*cos(q(5))*...
         cos(q(6))*cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7))) - q(1)*sin(q(4))*sin(q(5)) + cos(q(5))*sin(q(4))*(q(2)*...
         cos(q(4)) + q(3)*sin(q(4)))) - dq(7)*dq(8)*(sin(q(5))*(q(2)*sin(q(5)) - cos(q(4))*sin(q(6)) + q(1)*cos(q(4))*...
         cos(q(5)) + cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(5))*((cos(q(7)) - 1)*(cos(q(4))*sin(q(6)) - cos(q(6))*...
         sin(q(4))*sin(q(5))) - 2*cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) + q(2)*sin(q(5)) -...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(4))*cos(q(5))) + cos(q(5))*...
         sin(q(4))*(cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4)))) + cos(q(5))*sin(q(4))*...
         (cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(7)) - 1) - 2*cos(q(5))*cos(q(6))*...
         cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7)))) + dq(5)^2*cos(q(4))*(q(2)*cos(q(4)) + q(3)*sin(q(4))) - dq(5)*...
         dq(6)*(cos(q(4))*cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) - q(1)*sin(q(4))*sin(q(5)) + cos(q(5))*...
         sin(q(4))*(q(2)*cos(q(4)) + q(3)*sin(q(4)))) + dq(6)*dq(7)*(sin(q(5))*(q(2)*sin(q(5)) - cos(q(4))*sin(q(6)) +...
          q(1)*cos(q(4))*cos(q(5)) + cos(q(6))*sin(q(4))*sin(q(5))) - sin(q(5))*(q(2)*sin(q(5)) + q(1)*cos(q(4))*...
         cos(q(5))) + cos(q(5))^2*sin(q(4))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*sin(q(4))*(cos(q(5))*...
         cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))))) - dq(1)*dq(5)*cos(q(4)) + dq(4)*dq(5)*q(1)*...
         sin(q(4)) - dq(1)*dq(6)*cos(q(5))*sin(q(4)) - dq(1)*dq(7)*cos(q(5))*sin(q(4)) - dq(1)*dq(8)*cos(q(5))*...
         sin(q(4)) - dq(4)*dq(6)*q(1)*cos(q(4))*cos(q(5));
  djac_dq(3,1)=dq(8)^2*(sin(q(5))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) - 2*cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + q(3)*sin(q(5)) - sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(5))*sin(q(4))) + cos(q(4))*cos(q(5))*...
         (cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(7)) - 1) - 2*cos(q(5))*cos(q(6))*...
         cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7)))) - dq(2)*dq(4) - (q(2) - sin(q(8))*(cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) + sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6)))) -...
          (cos(q(7)) - 1)*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))) +...
          sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + 3*cos(q(8))*(cos(q(7))*(cos(q(6))*...
         sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) - sin(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5)))))*...
         (dq(5)*dq(6)*(cos(q(4))^2*cos(q(5)) + cos(q(5))*sin(q(4))^2) + dq(5)*dq(7)*(cos(q(4))^2*cos(q(5)) +...
          cos(q(5))*sin(q(4))^2) + dq(5)*dq(8)*(cos(q(4))^2*cos(q(5)) + cos(q(5))*sin(q(4))^2) + dq(5)^2*cos(q(4))*...
         sin(q(4)) - dq(6)^2*cos(q(4))*cos(q(5))^2*sin(q(4)) - dq(7)^2*cos(q(4))*cos(q(5))^2*sin(q(4)) - dq(8)^2*...
         cos(q(4))*cos(q(5))^2*sin(q(4))) + (q(1) + (cos(q(5))*cos(q(6))*sin(q(7)) + cos(q(5))*cos(q(7))*sin(q(6)))*(2*...
         cos(q(8)) - 2) - 3*sin(q(6) + q(7) + q(8))*cos(q(5)) + 2*sin(q(8))*(cos(q(5))*cos(q(6))*cos(q(7)) - cos(q(5))*...
         sin(q(6))*sin(q(7))) + cos(q(5))*sin(q(6))*(cos(q(7)) - 1) + cos(q(5))*cos(q(6))*sin(q(7)))*(dq(4)*dq(5)*...
         cos(q(4)) - dq(6)^2*cos(q(5))*sin(q(4))*sin(q(5)) - dq(7)^2*cos(q(5))*sin(q(4))*sin(q(5)) - dq(8)^2*cos(q(5))*...
         sin(q(4))*sin(q(5)) + dq(4)*dq(6)*cos(q(5))*sin(q(4)) + dq(4)*dq(7)*cos(q(5))*sin(q(4)) + dq(5)*dq(6)*...
         cos(q(4))*sin(q(5)) + dq(4)*dq(8)*cos(q(5))*sin(q(4)) + dq(5)*dq(7)*cos(q(4))*sin(q(5)) + dq(5)*dq(8)*...
         cos(q(4))*sin(q(5))) + dq(6)^2*(sin(q(5))*(q(3)*sin(q(5)) + q(1)*cos(q(5))*sin(q(4))) + cos(q(4))*cos(q(5))^2*...
         (q(3)*cos(q(4)) - q(2)*sin(q(4)))) + dq(4)^2*q(3) - (dq(5)^2*sin(q(4))^2 + dq(6)^2*(sin(q(5))^2 +...
          cos(q(4))^2*cos(q(5))^2) + dq(7)^2*(sin(q(5))^2 + cos(q(4))^2*cos(q(5))^2) + dq(8)^2*(sin(q(5))^2 + cos(q(4))^2*...
         cos(q(5))^2) + dq(4)^2)*(q(3) + sin(q(8))*(cos(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))) +...
          sin(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*sin(q(6)))) + (cos(q(7)) - 1)*(cos(q(4))*cos(q(6)) +...
          sin(q(4))*sin(q(5))*sin(q(6))) + (2*cos(q(8)) - 2)*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5)))) - sin(q(7))*(cos(q(4))*sin(q(6)) -...
          cos(q(6))*sin(q(4))*sin(q(5))) - 3*cos(q(8))*(cos(q(7))*(cos(q(4))*cos(q(6)) + sin(q(4))*sin(q(5))*...
         sin(q(6))) - sin(q(7))*(cos(q(4))*sin(q(6)) - cos(q(6))*sin(q(4))*sin(q(5))))) - dq(7)^2*(sin(q(5))*(sin(q(4))*...
         sin(q(6)) - q(3)*sin(q(5)) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5))) + cos(q(4))*cos(q(5))*...
         (cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))))) - dq(1)*dq(5)*sin(q(4)) + dq(2)*dq(6)*...
         sin(q(5)) + dq(2)*dq(7)*sin(q(5)) + dq(2)*dq(8)*sin(q(5)) + dq(4)*dq(7)*(sin(q(4))*sin(q(6)) - q(1)*cos(q(5))*...
         sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5))) + dq(6)*dq(8)*(sin(q(5))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - 2*cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + q(3)*...
         sin(q(5)) - sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(5))*sin(q(4))) -...
          sin(q(5))*(q(3)*sin(q(5)) + q(1)*cos(q(5))*sin(q(4))) - cos(q(4))*cos(q(5))^2*(q(3)*cos(q(4)) - q(2)*...
         sin(q(4))) + cos(q(4))*cos(q(5))*(cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(7)) -...
          1) - 2*cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(5))*sin(q(6))*sin(q(7)))) + dq(5)*dq(7)*(sin(q(4))*...
         (cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4)))) - q(1)*cos(q(4))*sin(q(5)) + cos(q(4))*...
         cos(q(5))*(q(2)*cos(q(4)) + q(3)*sin(q(4)))) - dq(5)*dq(8)*(sin(q(4))*(cos(q(5))*(q(3)*cos(q(4)) - q(2)*...
         sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(7)) - 1) - 2*cos(q(5))*cos(q(6))*cos(q(7)) + cos(q(5))*sin(q(6))*...
         sin(q(7))) + q(1)*cos(q(4))*sin(q(5)) - cos(q(4))*cos(q(5))*(q(2)*cos(q(4)) + q(3)*sin(q(4)))) - dq(4)*dq(8)*...
         ((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) - 2*cos(q(7))*(sin(q(4))*sin(q(6)) +...
          cos(q(4))*cos(q(6))*sin(q(5))) - sin(q(7))*(cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + q(1)*...
         cos(q(5))*sin(q(4))) + dq(7)*dq(8)*(sin(q(5))*((cos(q(7)) - 1)*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*...
         sin(q(5))) - 2*cos(q(7))*(sin(q(4))*sin(q(6)) + cos(q(4))*cos(q(6))*sin(q(5))) + q(3)*sin(q(5)) - sin(q(7))*...
         (cos(q(6))*sin(q(4)) - cos(q(4))*sin(q(5))*sin(q(6))) + q(1)*cos(q(5))*sin(q(4))) + sin(q(5))*(sin(q(4))*...
         sin(q(6)) - q(3)*sin(q(5)) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5))) + cos(q(4))*cos(q(5))*...
         (cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*cos(q(4)) - q(2)*sin(q(4)))) + cos(q(4))*cos(q(5))*(cos(q(5))*(q(3)*...
         cos(q(4)) - q(2)*sin(q(4))) + cos(q(5))*cos(q(6))*(cos(q(7)) - 1) - 2*cos(q(5))*cos(q(6))*cos(q(7)) +...
          cos(q(5))*sin(q(6))*sin(q(7)))) - dq(5)*dq(6)*(q(1)*cos(q(4))*sin(q(5)) - cos(q(4))*cos(q(5))*(q(2)*...
         cos(q(4)) + q(3)*sin(q(4))) + cos(q(5))*sin(q(4))*(q(3)*cos(q(4)) - q(2)*sin(q(4)))) + dq(5)^2*sin(q(4))*(q(2)*...
         cos(q(4)) + q(3)*sin(q(4))) - dq(6)*dq(7)*(sin(q(5))*(q(3)*sin(q(5)) + q(1)*cos(q(5))*sin(q(4))) + sin(q(5))*...
         (sin(q(4))*sin(q(6)) - q(3)*sin(q(5)) - q(1)*cos(q(5))*sin(q(4)) + cos(q(4))*cos(q(6))*sin(q(5))) + cos(q(4))*...
         cos(q(5))^2*(q(3)*cos(q(4)) - q(2)*sin(q(4))) + cos(q(4))*cos(q(5))*(cos(q(5))*cos(q(6)) - cos(q(5))*(q(3)*...
         cos(q(4)) - q(2)*sin(q(4))))) - dq(4)*dq(5)*q(1)*cos(q(4)) + dq(1)*dq(6)*cos(q(4))*cos(q(5)) + dq(1)*dq(7)*...
         cos(q(4))*cos(q(5)) + dq(1)*dq(8)*cos(q(4))*cos(q(5)) - dq(4)*dq(6)*q(1)*cos(q(5))*sin(q(4));

 